version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    steps:
      - run:
          name: install deps
          command: |
            apt-get update
            boostall=$(apt-cache search --names-only '^libboost1.[0-9]+-all-dev$' | sort | tail -n 1 | cut -f1 -d' ')
            apt-get install --no-install-recommends -y gcovr python2.7 gcc-7 build-essential cmake parallel $boostall
      - checkout
      - run:
          name: prepare build
          command: |
            mkdir build
            cd build
            cmake ..
      - run:
          name: run build
          command: |
            cd build
            make
